version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea_server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mariadb:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=5123
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    environment:
      - MYSQL_ROOT_PASSWORD=5123
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=5123
      - MYSQL_DATABASE=gitea
    restart: always
    ports:
      - "3306:3306"
    networks:
      - gitea
    volumes:
      - ./mariadb:/var/lib/mysql
